# Generated by Django 5.0.2 on 2024-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_is_active_alter_brand_name_productline"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="default", max_length=250),
        ),
    ]
